import { defineField, defineType, defineArrayMember } from "sanity";

export const homePageType = defineType({
  name: "homePage",
  title: "Ana Sayfa (Landing)",
  type: "document",
  groups: [
    { name: "hero", title: "01 — Hero" },
    { name: "about", title: "02 — Hakkında" },
    { name: "videos", title: "03 — Videolar" },
    { name: "gallery", title: "04 — Galeri" },
    { name: "contact", title: "05 — İletişim" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    // ── HERO ──────────────────────────────────────────────────────────────
    defineField({
      name: "heroEyebrow",
      title: "Hero Eyebrow",
      type: "string",
      group: "hero",
      description: "İsmin üzerindeki küçük etiket. Varsayılan: PERKÜSYON ŞOV SANATÇISI",
      placeholder: "PERKÜSYON ŞOV SANATÇISI",
    }),
    defineField({
      name: "heroLogo",
      title: "Hero Logo (Yazı/Görsel)",
      type: "image",
      group: "hero",
      options: { hotspot: true },
      description: "Samet Öztürk yazısı yerine gösterilecek yatay görsel (PNG önerilir). Kesiksiz ve tam görünür olacaktır.",
      fields: [
        defineField({
          name: "alt",
          title: "Alt Metni",
          type: "string",
          initialValue: "Samet",
        }),
      ],
    }),
    defineField({
      name: "heroFirstName",
      title: "İsim (1. satır)",
      type: "string",
      group: "hero",
      description: "Büyük harfle yazılacak. Varsayılan: SAMET",
      placeholder: "SAMET",
    }),
    defineField({
      name: "heroLastName",
      title: "İsim (2. satır / Soyisim)",
      type: "string",
      group: "hero",
      description: "Büyük harfle yazılacak. Varsayılan: ÖZTÜRK",
      placeholder: "ÖZTÜRK",
    }),
    defineField({
      name: "heroTagline",
      title: "Tagline",
      type: "string",
      group: "hero",
      description: "İsmin altındaki kısa tanım. Varsayılan: DARBUKA · BRASS · SAHNE PERFORMANSI",
      placeholder: "DARBUKA · BRASS · SAHNE PERFORMANSI",
    }),
    defineField({
      name: "heroCtaLabel",
      title: "CTA Buton Metni",
      type: "string",
      group: "hero",
      description: "Varsayılan: SAHNEYE DAVET ET",
      placeholder: "SAHNEYE DAVET ET",
    }),
    defineField({
      name: "heroVerticalText",
      title: "Sağ Dikey Metin",
      type: "string",
      group: "hero",
      description: "Hero'nun sağ kenarında döndürülmüş metin. Varsayılan: DARBUKA · BRASS · ORIENT",
      placeholder: "DARBUKA · BRASS · ORIENT",
    }),
    defineField({
      name: "heroVideoPoster",
      title: "Hero Arka Plan Görseli (Poster)",
      type: "image",
      group: "hero",
      options: { hotspot: true },
      description: "Videonun açılmasından önce gösterilecek tam ekran fotoğraf. Videonun ilk karesinden bir görsel önerilir.",
      fields: [
        defineField({
          name: "alt",
          title: "Alt Metni",
          type: "string",
          initialValue: "Samet Öztürk sahne",
        }),
      ],
    }),
    defineField({
      name: "heroVideoUrl",
      title: "Hero Arka Plan Video URL",
      type: "string",
      group: "hero",
      description: "Arka planda sessiz oynayacak video. Harici CDN MP4 linki girin — örn: https://res.cloudinary.com/.../video.mp4",
      placeholder: "https://res.cloudinary.com/...",
    }),

    // ── HAKKINDA ──────────────────────────────────────────────────────────
    defineField({
      name: "aboutSectionLabel",
      title: "Section Etiketi",
      type: "string",
      group: "about",
      description: "Varsayılan: 02 — HAKKINDA",
      placeholder: "02 — HAKKINDA",
    }),
    defineField({
      name: "aboutSectionTitle",
      title: "Section Başlığı",
      type: "string",
      group: "about",
      description: "Varsayılan: Sahnenin Ritmi",
      placeholder: "Sahnenin Ritmi",
    }),
    defineField({
      name: "aboutPhoto",
      title: "Fotoğraf (Sol Kolon)",
      type: "image",
      group: "about",
      options: { hotspot: true },
      description: "Dikey oran (2:3) tercih edilir.",
      fields: [
        defineField({
          name: "alt",
          title: "Alt Metni",
          type: "string",
          initialValue: "Samet Öztürk",
        }),
      ],
    }),
    defineField({
      name: "aboutBio",
      title: "Biyografi (Sağ Kolon)",
      type: "array",
      group: "about",
      description: "Rich text biyografi metni. İtalik ile önemli kelimeleri vurgulayabilirsiniz.",
      of: [
        defineArrayMember({
          type: "block",
          styles: [{ title: "Normal", value: "normal" }],
          marks: {
            decorators: [
              { title: "Bold", value: "strong" },
              { title: "Italic", value: "em" },
            ],
          },
        }),
      ],
    }),
    defineField({
      name: "aboutStats",
      title: "İstatistikler",
      type: "array",
      group: "about",
      description: "Sayaç animasyonlu stat kartları. Varsayılan: 17+ Yıl Sahne, 500+ Etkinlik, 50+ Marka",
      of: [{ type: "statItem" }],
      initialValue: [
        { _key: "stat1", value: "17+", label: "Yıl Sahne" },
        { _key: "stat2", value: "500+", label: "Etkinlik" },
        { _key: "stat3", value: "50+", label: "Marka" },
      ],
    }),

    // ── VİDEOLAR ──────────────────────────────────────────────────────────
    defineField({
      name: "videoSectionLabel",
      title: "Section Etiketi",
      type: "string",
      group: "videos",
      description: "Varsayılan: 03 — SHOWREEL & VİDEOLAR",
      placeholder: "03 — SHOWREEL & VİDEOLAR",
    }),
    defineField({
      name: "videoSectionTitle",
      title: "Section Başlığı",
      type: "string",
      group: "videos",
      description: "Varsayılan: Sahne Anları",
      placeholder: "Sahne Anları",
    }),
    defineField({
      name: "featuredVideoId",
      title: "Öne Çıkan Showreel — YouTube ID",
      type: "string",
      group: "videos",
      description: "YouTube URL'sindeki video ID. Büyük oynat butonu ile bu video gösterilir.",
      placeholder: "dQw4w9WgXcQ",
    }),
    defineField({
      name: "featuredVideoLabel",
      title: "Öne Çıkan Video Badge Metni",
      type: "string",
      group: "videos",
      description: "Varsayılan: SHOWREEL 2024",
      placeholder: "SHOWREEL 2024",
    }),
    defineField({
      name: "videos",
      title: "Video Listesi",
      type: "array",
      group: "videos",
      description: "Array içindeki sıralama (yukarı/aşağı kaydırarak) sitedeki sırayı belirler. Kategori filtresinde kullanılır.",
      of: [{ type: "videoItem" }],
    }),

    // ── GALERİ ────────────────────────────────────────────────────────────
    defineField({
      name: "gallerySectionLabel",
      title: "Section Etiketi",
      type: "string",
      group: "gallery",
      description: "Varsayılan: 04 — GALERİ",
      placeholder: "04 — GALERİ",
    }),
    defineField({
      name: "gallerySectionTitle",
      title: "Section Başlığı",
      type: "string",
      group: "gallery",
      description: "Varsayılan: Sahneden Kareler",
      placeholder: "Sahneden Kareler",
    }),
    defineField({
      name: "galleryImages",
      title: "Galeri Fotoğrafları",
      type: "array",
      group: "gallery",
      description: "Array içindeki sıralama (yukarı/aşağı kaydırarak) sitedeki sırayı belirler. İlk 9 görünür, 'Tümünü Göster' ile açılır.",
      of: [{ type: "galleryImage" }],
    }),

    // ── İLETİŞİM ──────────────────────────────────────────────────────────
    defineField({
      name: "contactSectionLabel",
      title: "Section Etiketi",
      type: "string",
      group: "contact",
      description: "Varsayılan: 05 — İLETİŞİM",
      placeholder: "05 — İLETİŞİM",
    }),
    defineField({
      name: "contactSectionTitle",
      title: "Section Başlığı",
      type: "string",
      group: "contact",
      description: "Varsayılan: Sahneye Davet Et",
      placeholder: "Sahneye Davet Et",
    }),
    defineField({
      name: "contactSectionSubtitle",
      title: "Altyazı",
      type: "string",
      group: "contact",
      description: "Başlığın altında küçük italic metin. Varsayılan: Düğün, kurumsal etkinlik...",
      placeholder: "Düğün, kurumsal etkinlik, özel gece veya uluslararası proje.",
    }),
    defineField({
      name: "contactEmail",
      title: "E-posta Adresi",
      type: "string",
      group: "contact",
      placeholder: "samet@example.com",
    }),
    defineField({
      name: "contactPhone",
      title: "Telefon Numarası",
      type: "string",
      group: "contact",
      description: "Arama uygulamasına yönlendiren telefon numarası. Örn: +905551234567",
      placeholder: "+905551234567",
    }),
    defineField({
      name: "contactInstagram",
      title: "Instagram Handle",
      type: "string",
      group: "contact",
      description: "@ olmadan — örn: sametozturk",
      placeholder: "sametozturk",
    }),
    defineField({
      name: "contactInstagramUrl",
      title: "Instagram URL",
      type: "url",
      group: "contact",
      placeholder: "https://instagram.com/sametozturk",
    }),
    defineField({
      name: "contactYoutubeUrl",
      title: "YouTube URL",
      type: "url",
      group: "contact",
      placeholder: "https://youtube.com/@sametozturk",
    }),
    defineField({
      name: "contactFacebookUrl",
      title: "Facebook URL",
      type: "url",
      group: "contact",
      placeholder: "https://facebook.com/sametozturk",
    }),
    defineField({
      name: "contactBgVideoUrl",
      title: "İletişim Arka Plan Video URL",
      type: "string",
      group: "contact",
      description: "Arka planda sessiz oynayacak video. Harici CDN MP4 linki girin — örn: https://res.cloudinary.com/.../video.mp4",
      placeholder: "https://res.cloudinary.com/...",
    }),

    // ── SEO ───────────────────────────────────────────────────────────────
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
  ],
});
